create extension if not exists "pgcrypto";

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  status text not null default 'pending' check (status in ('pending', 'active', 'completed', 'cancelled')),
  current_step integer not null default 0 check (current_step >= 0 and current_step <= 10),
  max_participants integer not null default 12 check (max_participants >= 2 and max_participants <= 200),
  started_at timestamptz,
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  display_name text not null check (length(trim(display_name)) > 0),
  role text not null default 'participant' check (role in ('host', 'participant')),
  status text not null default 'joined' check (status in ('joined', 'active', 'completed', 'left')),
  join_token text not null,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, id),
  unique (session_id, join_token)
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  group_no integer not null check (group_no > 0),
  assigned_step integer not null check (assigned_step >= 1 and assigned_step <= 10),
  group_type text not null default 'pair' check (group_type in ('pair', 'trio', 'custom')),
  status text not null default 'assigned' check (status in ('assigned', 'active', 'completed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, id),
  unique (session_id, assigned_step, group_no)
);

create table if not exists public.group_members (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  group_id uuid not null,
  participant_id uuid not null,
  seat_no integer check (seat_no > 0),
  created_at timestamptz not null default now(),
  foreign key (session_id, group_id) references public.groups(session_id, id) on delete cascade,
  foreign key (session_id, participant_id) references public.participants(session_id, id) on delete cascade,
  unique (group_id, participant_id),
  unique (group_id, seat_no)
);

create table if not exists public.participant_steps (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  participant_id uuid not null,
  step_no integer not null check (step_no >= 1 and step_no <= 10),
  payload jsonb not null default '{}'::jsonb,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (session_id, participant_id) references public.participants(session_id, id) on delete cascade,
  unique (session_id, participant_id, step_no)
);

create table if not exists public.participant_result (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  participant_id uuid not null,
  result_type text,
  score numeric,
  summary jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (session_id, participant_id) references public.participants(session_id, id) on delete cascade,
  unique (session_id, participant_id)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(id) on delete set null,
  participant_id uuid references public.participants(id) on delete set null,
  event_name text not null check (length(trim(event_name)) > 0),
  event_step integer check (event_step is null or (event_step >= 1 and event_step <= 10)),
  source text not null default 'edge_function',
  payload jsonb not null default '{}'::jsonb,
  event_at timestamptz not null default now()
);

create index if not exists idx_sessions_status on public.sessions(status);
create index if not exists idx_sessions_created_at on public.sessions(created_at desc);

create index if not exists idx_participants_session on public.participants(session_id);
create index if not exists idx_participants_status on public.participants(status);

create index if not exists idx_groups_session_step on public.groups(session_id, assigned_step);
create index if not exists idx_group_members_session on public.group_members(session_id);
create index if not exists idx_group_members_participant on public.group_members(participant_id);

create index if not exists idx_participant_steps_session_step on public.participant_steps(session_id, step_no);
create index if not exists idx_participant_steps_participant on public.participant_steps(participant_id);

create index if not exists idx_participant_result_session on public.participant_result(session_id);

create index if not exists idx_analytics_events_session_time on public.analytics_events(session_id, event_at desc);
create index if not exists idx_analytics_events_name_time on public.analytics_events(event_name, event_at desc);
create index if not exists idx_analytics_events_participant on public.analytics_events(participant_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sessions_set_updated_at on public.sessions;
create trigger trg_sessions_set_updated_at
before update on public.sessions
for each row execute function public.set_updated_at();

drop trigger if exists trg_participants_set_updated_at on public.participants;
create trigger trg_participants_set_updated_at
before update on public.participants
for each row execute function public.set_updated_at();

drop trigger if exists trg_groups_set_updated_at on public.groups;
create trigger trg_groups_set_updated_at
before update on public.groups
for each row execute function public.set_updated_at();

drop trigger if exists trg_participant_steps_set_updated_at on public.participant_steps;
create trigger trg_participant_steps_set_updated_at
before update on public.participant_steps
for each row execute function public.set_updated_at();

drop trigger if exists trg_participant_result_set_updated_at on public.participant_result;
create trigger trg_participant_result_set_updated_at
before update on public.participant_result
for each row execute function public.set_updated_at();
